"""
TrackingStore — reads and writes tracking.yml for per-table migration state.

No other module should read or write tracking.yml directly.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Literal

import yaml

from tools.dbt.flink_dbt_migrate.sl_discovery_mgr import TableEntry

_HEADER = "# Auto-generated by flink-sql-migrate-dbt — do not edit manually\n"


@dataclass
class TrackingRecord:
    table_name: str
    relative_path: str
    dml_sha256: str
    status: Literal["done", "failed", "skipped"]
    error: str | None
    migrated_at: str  # ISO-8601


class TrackingStore:
    """In-memory view of tracking.yml; load/save handles all YAML I/O."""

    def __init__(self, records: dict[str, TrackingRecord] | None = None) -> None:
        self._records: dict[str, TrackingRecord] = records or {}

    # ------------------------------------------------------------------
    # Construction
    # ------------------------------------------------------------------

    @classmethod
    def load(cls, path: Path) -> "TrackingStore":
        """Read tracking.yml from *path*; return an empty store if the file is absent."""
        if not path.is_file():
            return cls()
        raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        tables: dict[str, TrackingRecord] = {}
        for table_name, data in (raw.get("tables") or {}).items():
            tables[table_name] = TrackingRecord(
                table_name=table_name,
                relative_path=data.get("relative_path", ""),
                dml_sha256=data.get("dml_sha256", ""),
                status=data.get("status", "failed"),
                error=data.get("error"),
                migrated_at=data.get("migrated_at", ""),
            )
        return cls(tables)

    # ------------------------------------------------------------------
    # Query
    # ------------------------------------------------------------------

    def should_migrate(self, entry: TableEntry, force: bool = False) -> bool:
        """Return True when the table should be (re-)migrated.

        True when any of:
        - *force* is True
        - no record exists for this table
        - the stored status is not ``done``
        - the stored DML SHA differs from *entry.dml_sha256*
        """
        if force:
            return True
        rec = self._records.get(entry.table_name)
        if rec is None:
            return True
        if rec.status != "done":
            return True
        if rec.dml_sha256 != entry.dml_sha256:
            return True
        return False

    # ------------------------------------------------------------------
    # Mutation
    # ------------------------------------------------------------------

    def record(
        self,
        table_name: str,
        status: Literal["done", "failed", "skipped"],
        sha256: str,
        relative_path: str,
        error: str | None = None,
    ) -> None:
        """Upsert one record with the current UTC timestamp."""
        self._records[table_name] = TrackingRecord(
            table_name=table_name,
            relative_path=relative_path,
            dml_sha256=sha256,
            status=status,
            error=error,
            migrated_at=datetime.now(tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%S"),
        )

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def save(self, path: Path) -> None:
        """Write tracking.yml atomically (write to .tmp then rename)."""
        tables: dict[str, dict] = {}
        for rec in self._records.values():
            tables[rec.table_name] = {
                "relative_path": rec.relative_path,
                "dml_sha256": rec.dml_sha256,
                "status": rec.status,
                "error": rec.error,
                "migrated_at": rec.migrated_at,
            }
        content = _HEADER + yaml.dump(
            {"tables": tables},
            default_flow_style=False,
            allow_unicode=True,
            sort_keys=True,
        )
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp_path = path.with_suffix(".yml.tmp")
        tmp_path.write_text(content, encoding="utf-8")
        tmp_path.rename(path)

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------

    def summary(self) -> dict[str, int]:
        """Return counts by status: ``{done: N, failed: M, skipped: K}``."""
        counts: dict[str, int] = {"done": 0, "failed": 0, "skipped": 0}
        for rec in self._records.values():
            counts[rec.status] = counts.get(rec.status, 0) + 1
        return counts
