site_name: Flink Tools for Agents
repo_url: https://github.com/jbcodeforce/flink-tools-for-agents
site_url: https://jbcodeforce.github.io/flink-tools-for-agents
copyright: Copyright &copy; 2024 - 2026 Jerome Boyer

nav:
  - Home: index.md
  - Methodology:
    - Day-to-day with the agents: methodology/index.md
    - Day-to-day DE methodology: https://jbcodeforce.github.io/flink-studies/methodology/data_eng_101/
    - dbt summary: https://jbcodeforce.github.io/flink-studies/coding/dbt/#confluent-cloud-flink-specifics
  - Flink Deploy:
    - Overview: flink/index.md
    - Manifest: manifest/index.md
  - dbt Projects:
    - Overview: dbt/index.md
  - Kafka & Schema Registry:
    - Overview: kafka/index.md
  - Skills:
    - Using Skills with Bob/Claude: skills/index.md

theme:
  name: material
  logo: images/flink-header-logo.svg
  favicon: images/logo-blue.drawio.png
  palette:
    - scheme: default
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - content.tabs.link
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.caret
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

plugins:
  - search

docs_dir: docs
site_dir: site
extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/jbcodeforce'
    - icon: fontawesome/brands/linkedin
      link: 'https://linkedin.com/in/jeromeboyer'
